# General File Paths
paths:
  data_path: "data/"
  output_path: "output/"

# ROS Topics
topics:
  img_topic: "/girona1000/flir_spinnaker_camera/image_raw/compressed"
  odo_topic: "/girona1000/navigator/odometry"
  info_topic: "/girona1000/flir_spinnaker_camera/camera_info"
  sonar_topic: "/girona1000/marinesonic_scoutmkii_sidescan/snr2_data"
  nav_topic: "/girona1000/navigator/navigation"

extrinsics:
  sonar:  [0.40, 0.00, 0.45]          # Translation from base to sonar in meters (x, y, z)
  camera: [0.50, 0.00, 0.72]          # Translation from base to camera in meters (x, y, z)

photogrammetry:
  enabled: false                      # Whether to run photogrammetry reconstruction (Default: false)

  features:
    contrast_threshold: 0.002         # SIFT contrast threshold for feature detection (Default 0.0067)
    max_num_features: 8192            # Maximum number of SIFT features to detect (Default 8192)
    pos_std: [0.1, 0.1, 0.1]          # Standard deviation (weight) in meters of the position prior
    max_distance: 10.0                # Maximum distance in meters for matching features between images

  sparse:
    ba_global_ratio: 1.1              # The relative growth rates after which to perform global bundle adjustment (Default: 1.1)
    ba_global_frames_freq: 500        # The frame growth rate after which to perform global bundle adjustment (Default: 500)
    ba_global_points_freq: 250000     # The pointcloud growth rates after which to perform global bundle adjustment (Default: 250000)
    ba_global_max_num_iterations: 50  # The maximum number of global bundle adjustment iterations (Default: 50)
    ba_global_max_refinements: 5      # The thresholds for iterative bundle adjustment refinements (Default: 5)

  dense:
    max_image_size: 2000              # Maximum image size in either dimension for dense reconstruction (Default: -1)
    check_num_images: 50              # Number of overlapping images to transitively check for fusing points (Default: 50)
    cache_size: 32.0                  # Cache size in gigabytes for fusion (Default: 32.0)

  mesh:
    mesh_depth: 12                    # Depth parameter for Poisson surface resolution (Default: 8)
    reduce_perc: 90.0                 # Percentage of faces to keep when simplifying the mesh (Default: 90.0)
    tex_size: 32768                   # Texture size for UV mapping (Default: 1024)

process_acoustic:                     # Generates an XTF and a PNG using the SSS data
  enabled: false
  sonar_name: "ARC Scout Mk II"       # Name of the sonar for labeling outputs
  sample_dtype: uint16                # The sample datatype used (options: uint8, uint16, uint32, float32)

optical_registration:
  enabled: true